### ISSUE TITLE
[ISSUE FIXED] Not transfering any pokemon when NotTransferPokemonsThatCanEvolve is enabled

### ISSUE THREAD

**Issue by AlexHolo** [Spegeli/Pokemon-Go-Rocket-API#79]
I've downloaded the bot and edited the settings and so on but i have the problem that the bot won't transfer any of my pokemon? I have 233/250 and there are many duplicated pokemon and also with a low perfection but the bot ignored it at all.
These are my settings:
http://puu.sh/qdEih.png

I have never seen a line in the Console that he even tried to transfer.. nothing..

**Comment by Spegeli** [comment]
Disable: NotTransferPokemonsThatCanEvolve

Its a new function which i implant with the last release and it seems i made something wrong.
But currently this option is useless because it always will Evolve before Transfer.

Will fix this issue later the day.

**Comment by Spegeli** [comment]
Uploaded a new Version where this bug should be fixed.
Can you pls test it and then let me know if its working correct or not.

**Comment by Superkillen** [comment]
I had the same problem... my settings https://gyazo.com/0a5b97759901d8326fcd80954449ca87
and this is what the bot says: https://gyazo.com/9a882d028106e7c928f5c33baac938c9

**Comment by AlexHolo** [comment]
Thanks for the quick support but sadly it isn't fixed for me yet.

These are my settings:
http://puu.sh/qdLmm.png
For example:
I have 10 Sandshrew's with a WP between 10-320 and only 40 Sandshrew Candy. So iam not able to evolve any of them but they are not getting transfered?
http://puu.sh/qdLuu.jpg

Greetz.

**Comment by Spegeli** [comment]
Ok sorry was a mistake, the NotTransferPokemonsThatCanEvolve is working as intend.
When NotTransferPokemonsThatCanEvolve is enabled, it will keep ALL Pokemon for where we have enough Candies, no matter if they on the Evolve List or not.

**Comment by AlexHolo** [comment]
Alright, it works great again, thx for the fast support and the nice bot.
+rep
